# -------------------------------------------------------------------------
# Copyright (c) 2025 Huawei Technologies Co., Ltd.
# This file is part of the MindStudio project.
#
# MindStudio is licensed under Mulan PSL v2.
# You can use this software according to the terms and conditions of the Mulan PSL v2.
# You may obtain a copy of Mulan PSL v2 at:
#
#    http://license.coscl.org.cn/MulanPSL2
#
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
# EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
# MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
# See the Mulan PSL v2 for more details.
# -------------------------------------------------------------------------
from msconfig.meta_config import MetaConfig


class TablesConfig(MetaConfig):
    DATA = {
        'TaskInfoMap': [
            ('model_id', 'INTEGER,null'),
            ('op_name', 'TEXT,null'),
            ('stream_id', 'INTEGER,null'),
            ('task_id', 'INTEGER,null'),
            ('block_num', 'INTEGER,null'),
            ('mix_block_num', 'INTEGER,null'),
            ('op_state', 'TEXT,null'),
            ('task_type', 'TEXT,null'),
            ('op_type', 'TEXT,null'),
            ('index_id', 'INTEGER,null'),
            ('thread_id', 'INTEGER,null'),
            ('timestamp', 'NUMERIC,null'),
            ('batch_id', 'INTEGER,null'),
            ('tensor_num', 'INTEGER,null'),
            ('input_formats', 'TEXT,null'),
            ('input_data_types', 'TEXT,null'),
            ('input_shapes', 'TEXT,null'),
            ('output_formats', 'TEXT,null'),
            ('output_data_types', 'TEXT,null'),
            ('output_shapes', 'TEXT,null'),
            ('device_id', 'INTEGER,null'),
            ('context_id', 'INTEGER,null'),
            ('op_flag', 'TEXT,null'),
            ('hashid', 'TEXT,null'),
        ],
        'GeHashInfoMap': [
            ('hash_key', 'TEXT,null'),
            ('hash_value', 'TEXT,null')
        ],
        'TypeHashInfoMap': [
            ('hash_key', 'TEXT,null'),
            ('hash_value', 'TEXT,null'),
            ('level', 'TEXT,null')
        ],
        'SessionInfoMap': [
            ('model_id', 'INTEGER,null'),
            ('graph_id', 'INTEGER,null'),
            ('session_id', 'INTEGER,null'),
            ('mod', 'INTEGER,null'),
            ('timestamp', 'NUMERIC,null')
        ],
        'GeFusionOpInfoMap': [
            ('model_id', 'INTEGER,null'),
            ('fusion_name', 'TEXT,null'),
            ('fusion_op_nums', 'INTEGER,null'),
            ('op_names', 'TEXT,null'),
            ('memory_input', 'TEXT,null'),
            ('memory_output', 'TEXT,null'),
            ('memory_weight', 'TEXT,null'),
            ('memory_workspace', 'TEXT,null'),
            ('memory_total', 'TEXT,null')
        ],
        'GEHostInfoMap': [
            ('thread_id', 'INTEGER,null'),
            ('op_type', 'TEXT,null'),
            ('event_type', 'TEXT,null'),
            ('start_time', 'INTEGER,null'),
            ('end_time', 'INTEGER,null'),
            ('op_name', 'TEXT,null')
        ],
        'GeLogicStreamInfoMap': [
            ('physic_stream', 'INTEGER,null'),
            ('logic_stream', 'INTEGER,null')
        ],
        'CaptureStreamInfoMap': [
            ('device_id', 'INTEGER,null'),
            ('model_id', 'INTEGER,null'),
            ('original_stream_id', 'INTEGER,null'),
            ('stream_id', 'INTEGER,null'),
            ('batch_id', 'INTEGER,null'),
            ('capture_status', 'INTEGER,null'),
            ('timestamp', 'NUMERIC,null')
        ],
        'OriginalDataMap': [
            ('common', 'TEXT,null'),
            ('pid', 'INT,null'),
            ('tid', 'INT,null'),
            ('core', 'INT,null'),
            ('timestamp', 'NUMERIC,null'),
            ('pmucount', 'INT,null'),
            ('pmuevent', 'CHAR(10),null'),
            ('ip', 'TEXT,null'),
            ('function', 'TEXT,null'),
            ('offset', 'TEXT,null'),
            ('module', 'TEXT,null'),
            ('callstack', 'TEXT,null'),
            ('replayid', 'INT,null')
        ],
        'ApiCallMap': [
            ('entry_time', 'INTEGER,null'),
            ('exit_time', 'INTEGER,null'),
            ('api', 'TEXT,null'),
            ('thread', 'INTEGER,null'),
            ('stream_id', 'INTEGER,null'),
            ('task_id', 'TEXT,null'),
            ('batch_id', 'TEXT,null'),
            ('data_size', 'INTEGER,null'),
            ('memcpy_direction', 'TEXT,null')
        ],
        'TimeLineMap': [
            ('replayid', 'INTEGER,null'),
            ('tasktype', 'INTEGER,null'),
            ('task_id', 'INTEGER,null'),
            ('stream_id', 'INTEGER,null'),
            ('taskstate', 'INTEGER,null'),
            ('timestamp', 'NUMERIC,null'),
            ('thread', 'INTEGER,null'),
            ('device_id', 'INTEGER,null'),
            ('mode', 'INTEGER,null')
        ],
        'EventCounterMap': [
            ('replayid', 'INTEGER,null'),
            ('tasktype', 'INTEGER,null'),
            ('task_id', 'INTEGER,null'),
            ('stream_id', 'INTEGER,null'),
            ('overflow', 'INTEGER,null'),
            ('overflowcycle', 'INTEGER,null'),
            ('timestamp', 'NUMERIC,null'),
            ('event1', 'TEXT,null'),
            ('event2', 'TEXT,null'),
            ('event3', 'TEXT,null'),
            ('event4', 'TEXT,null'),
            ('event5', 'TEXT,null'),
            ('event6', 'TEXT,null'),
            ('event7', 'TEXT,null'),
            ('event8', 'TEXT,null'),
            ('task_cyc', 'TEXT,null'),
            ('block', 'INTEGER,null'),
            ('thread', 'INTEGER,null'),
            ('device_id', 'INTEGER,null'),
            ('mode', 'INTEGER,null')
        ],
        'StepTraceMap': [
            ('index_id', 'INTEGER,null'),
            ('model_id', 'INTEGER,null'),
            ('timestamp', 'NUMERIC, null'),
            ('stream_id', 'INTEGER,null'),
            ('task_id', 'INTEGER,null'),
            ('tag_id', 'INTEGER,null')
        ],
        'TsMemcpyMap': [
            ('timestamp', 'NUMERIC, null'),
            ('stream_id', 'INTEGER,null'),
            ('task_id', 'INTEGER,null'),
            ('task_state', 'INTEGER,null')
        ],
        'TsMemcpyCalculationMap': [
            ('stream_id', 'INTEGER,null'),
            ('task_id', 'INTEGER,null'),
            ('receive_time', 'INTEGER,null'),
            ('start_time', 'INTEGER,null'),
            ('end_time', 'INTEGER,null'),
            ('duration', 'INTEGER,null'),
            ('name', 'TEXT,null'),
            ('type', 'TEXT,null')
        ],
        'ReportTaskMap': [
            ('timeratio', 'REAL,null'),
            ('time', 'REAL,null'),
            ('count', 'INTEGER,null'),
            ('avg', 'REAL,null'),
            ('min', 'REAL,null'),
            ('max', 'REAL,null'),
            ('waiting', 'REAL,null'),
            ('running', 'REAL,null'),
            ('pending', 'REAL,null'),
            ('type', 'TEXT,null'),
            ('api', 'TEXT,null'),
            ('task_id', 'INTEGER,null'),
            ('stream_id', 'INTEGER,null'),
            ('device_id', 'INTEGER,null'),
            ('batch_id', 'INTEGER,null')
        ],
        'TaskTimeMap': [
            ('replayid', 'INTEGER,null'),
            ('device_id', 'INTEGER,null'),
            ('api', 'INTEGER,null'),
            ('apirowid', 'INTEGER,null'),
            ('tasktype', 'INTEGER,null'),
            ('task_id', 'INTEGER,null'),
            ('stream_id', 'INTEGER,null'),
            ('waittime', 'NUMERIC,null'),
            ('pendingtime', 'NUMERIC,null'),
            ('running', 'NUMERIC,null'),
            ('complete', 'NUMERIC,null'),
            ('index_id', 'INTEGER,null'),
            ('model_id', 'INTEGER,null'),
            ('batch_id', 'INTEGER,null')
        ],
        'TsOriginalDataMap': [
            ('replayid', 'INTEGER,null'),
            ('timestamp', 'NUMERIC,null'),
            ('pc', 'TEXT,null'),
            ('callstack', 'TEXT,null'),
            ('event', 'TEXT,null'),
            ('count', 'INTEGER,null'),
            ('function', 'TEXT,null')
        ],
        'AICoreOriginalDataMap': [
            ('mode', 'INTEGER,null'),
            ('replayid', 'INTEGER,null'),
            ('timestamp', 'NUMERIC,null'),
            ('coreid', 'INTEGER,null'),
            ('task_cyc', 'Text,null'),
            ('event1', 'Text,null'),
            ('event2', 'Text,null'),
            ('event3', 'Text,null'),
            ('event4', 'Text,null'),
            ('event5', 'Text,null'),
            ('event6', 'Text,null'),
            ('event7', 'Text,null'),
            ('event8', 'Text,null'),
            ('event9', 'Text,null'),
            ('event10', 'Text,null'),
        ],
        'NicOriginalDataMap': [
            ('device_id', 'INTEGER,null'),
            ('replayid', 'INTEGER,null'),
            ('timestamp', 'NUMERIC,null'),
            ('bandwidth', 'INTEGER,null'),
            ('rxpacket', 'REAL,null'),
            ('rxbyte', 'REAL,null'),
            ('rxpackets', 'REAL,null'),
            ('rxbytes', 'REAL,null'),
            ('rxerrors', 'REAL,null'),
            ('rxdropped', 'REAL,null'),
            ('txpacket', 'REAL,null'),
            ('txbyte', 'REAL,null'),
            ('txpackets', 'REAL,null'),
            ('txbytes', 'REAL,null'),
            ('txerrors', 'REAL,null'),
            ('txdropped', 'REAL,null'),
            ('funcid', 'INTEGER,null')
        ],
        'NicReportDataMap': [
            ('device_id', 'INTEGER,null'),
            ('duration', 'TEXT,null'),
            ('bandwidth', 'TEXT,null'),
            ('rxbandwidth', 'TEXT,null'),
            ('txbandwidth', 'TEXT,null'),
            ('rxpacket', 'TEXT,null'),
            ('rxerrorrate', 'TEXT,null'),
            ('rxdroppedrate', 'TEXT,null'),
            ('txpacket', 'TEXT,null'),
            ('txerrorrate', 'TEXT,null'),
            ('txdroppedrate', 'TEXT,null'),
            ('funcid', 'INTEGER,null')
        ],
        'DvppOriginalDataMap': [
            ('device_id', 'TEXT,null'),
            ('replayid', 'TEXT,null'),
            ('timestamp', 'NUMERIC,null'),
            ('dvppid', 'TEXT,null'),
            ('enginetype', 'TEXT,null'),
            ('engineid', 'TEXT,null'),
            ('alltime', 'REAL,null'),
            ('allframe', 'REAL,null'),
            ('allutilization', 'TEXT,null'),
            ('proctime', 'REAL,null'),
            ('procframe', 'REAL,null'),
            ('procutilization', 'TEXT,null'),
            ('lasttime', 'REAL,null'),
            ('lastframe', 'REAL,null')
        ],
        'DvppReportDataMap': [
            ('dvppid', 'TEXT,null'),
            ('device_id', 'TEXT,null'),
            ('enginetype', 'TEXT,null'),
            ('engineid', 'TEXT,null'),
            ('alltime', 'TEXT,null'),
            ('allframe', 'TEXT,null'),
            ('allutilization', 'TEXT,null')
        ],
        'StreamMap': [
            ('replayid', 'INTEGER, null'),
            ('device_id', 'INTEGER, null'),
            ('stream_id', 'INTEGER, null'),
            ('task_id', 'INTEGER, null'),
            ('tasktype', 'INTEGER, null'),
            ('waittime', 'INTEGER, null'),
            ('pendingtime', 'INTEGER,null'),
            ('runtime', 'INTEGER,null'),
            ('completetime', 'INTEGER, null'),
            ('api', 'INTEGER, null'),
            ('apirowid', 'INTEGER, null'),
            ('eventid', 'INTEGER, null'),
            ('streamname', 'TEXT, null')
        ],
        'LLCOriginalDataMap': [
            ('device_id', 'INT,null'),
            ('replayid', 'INT,null'),
            ('timestamp', 'NUMERIC,null'),
            ('counts', 'INT,null'),
            ('unit', 'VARCHAR,null'),
            ('event', 'VARCHAR,null')
        ],
        'LLCMetricDataMap': [
            ('device_id', 'INT,null'),
            ('replayid', 'INT,null'),
            ('timestamp', 'NUMERIC,null'),
            ('read_allocate', 'REAL,null'),
            ('read_noallocate', 'REAL,null'),
            ('read_hit', 'REAL,null'),
            ('write_allocate', 'REAL,null'),
            ('write_noallocate', 'REAL,null'),
            ('write_hit', 'REAL,null')
        ],
        'LLCDsidDataMap': [
            ('device_id', 'INT,null'),
            ('replayid', 'INT,null'),
            ('timestamp', 'NUMERIC,null'),
            ('dsid0', 'REAL,null'),
            ('dsid1', 'REAL,null'),
            ('dsid2', 'REAL,null'),
            ('dsid3', 'REAL,null'),
            ('dsid4', 'REAL,null'),
            ('dsid5', 'REAL,null'),
            ('dsid6', 'REAL,null'),
            ('dsid7', 'REAL,null')
        ],
        'ai_core_statusMap': [
            ('mode', 'INTEGER,null'),
            ('replayid', 'INTEGER,null'),
            ('device_id', 'INTEGER,null'),
            ('timestamp', 'NUMERIC,null'),
            ('aicorenumber', 'INTEGER,null'),
            ('aicorestate', 'TEXT,null')
        ],
        'ai_vector_statusMap': [
            ('mode', 'INTEGER,null'),
            ('replayid', 'INTEGER,null'),
            ('device_id', 'INTEGER,null'),
            ('timestamp', 'NUMERIC,null'),
            ('aivnumber', 'INTEGER,null'),
            ('aivstate', 'TEXT,null')
        ],
        'RuntimeTrackMap': [
            ('device_id', 'INTEGER,null'),
            ('timestamp', 'NUMERIC,null'),
            ('task_type', 'INTEGER,null'),
            ('stream_id', 'INTEGER,null'),
            ('task_id', 'INTEGER,null'),
            ('thread', 'INTEGER,null'),
            ('batch_id', 'INTEGER,null'),
        ],
        'TsTrackMap': [
            ('mode', 'INTEGER,null'),
            ('replayid', 'INTEGER,null'),
            ('device_id', 'INTEGER,null'),
            ('timestamp', 'NUMERIC,null'),
            ('eventname', 'TEXT,null'),
            ('tasktype', 'INTEGER,null'),
            ('stream_id', 'INTEGER,null'),
            ('task_id', 'INTEGER,null')
        ],
        'DDROriginalDataMap': [
            ('device_id', 'INT,null'),
            ('replayid', 'INT,null'),
            ('timestamp', 'NUMERIC,null'),
            ('counts', 'INT,null'),
            ('unit', 'VARCHAR,null'),
            ('event', 'VARCHAR,null')
        ],
        'DDRMetricDataMap': [
            ('device_id', 'INT,null'),
            ('replayid', 'INT,null'),
            ('timestamp', 'NUMERIC,null'),
            ('flux_read', 'REAL,null'),
            ('flux_write', 'REAL,null'),
            ('fluxid_read', 'REAL,null'),
            ('fluxid_write', 'REAL,null')
        ],
        'LLCBandwidthMap': [
            ('device_id', 'INT,null'),
            ('timestamp', 'NUMERIC,null'),
            ('read_hit_rate', 'REAL,null'),
            ('read_total', 'REAL,null'),
            ('read_hit', 'REAL,null'),
            ('write_hit_rate', 'REAL,null'),
            ('write_total', 'REAL,null'),
            ('write_hit', 'REAL,null')
        ],
        'LLCCapacityMap': [
            ('device_id', 'INT,null'),
            ('timestamp', 'NUMERIC,null'),
            ('ctrlcpu', 'REAL,null'),
            ('aicpu', 'REAL,null')
        ],
        'sysmemMap': [
            ('timestamp', 'NUMERIC,null'),
            ('memtotal', 'INTEGER,null'),
            ('memfree', 'INTEGER,null'),
            ('buffers', 'INTEGER,null'),
            ('cached', 'INTEGER,null'),
            ('shmem', 'INTEGER,null'),
            ('commitlimit', 'INTEGER,null'),
            ('committed_as', 'INTEGER,null'),
            ('hugepages_total', 'INTEGER,null'),
            ('hugepages_free', 'INTEGER,null'),
            ('unit', 'TEXT,null')
        ],
        'pidmemMap': [
            ('timestamp', 'NUMERIC,null'),
            ('name', 'TEXT,null'),
            ('size', 'INTEGER,null'),
            ('resident', 'INTEGER,null'),
            ('shared', 'INTEGER,null'),
            ('pid', 'INTEGER,null')
        ],
        'SysCpuUsageDataMap': [
            ('timestamp', 'NUMERIC,null'),
            ('cpun', 'TEXT,null'),
            ('user', 'REAL,null'),
            ('nice', 'REAL,null'),
            ('sys', 'REAL,null'),
            ('idle', 'REAL,null'),
            ('iowait', 'REAL,null'),
            ('irq', 'REAL,null'),
            ('soft', 'REAL,null'),
            ('steal', 'REAL,null'),
            ('guest', 'REAL,null'),
            ('gnice', 'REAL,null'),
            ('cputype', 'TEXT,null')
        ],
        'ProCpuUsageDataMap': [
            ('pid', 'INT,null'),
            ('process_name', 'VARCHAR,null'),
            ('utime', 'REAL,null'),
            ('stime', 'REAL,null'),
            ('cutime', 'REAL,null'),
            ('cstime', 'REAL,null'),
            ('timestamp', 'NUMERIC,null'),
            ('sys_usage', 'REAL,null')
        ],
        'AclDataMap': [
            ('api_name', 'TEXT,null'),
            ('api_type', 'TEXT,null'),
            ('start_time', 'INTEGER,null'),
            ('end_time', 'INTEGER,null'),
            ('process_id', 'INTEGER,null'),
            ('thread_id', 'INTEGER,null')
        ],
        'ModifiedTaskTimeMap': [
            ('task_id', 'INTEGER, null'),
            ('stream_id', 'INTEGER, null'),
            ('start_time', 'INTEGER,null'),
            ('duration_time', 'INTEGER, null'),
            ('wait_time', 'INTEGER, null'),
            ('task_type', 'INTEGER,null'),
            ('index_id', 'INTEGER, null'),
            ('model_id', 'INTEGER, null'),
            ('batch_id', 'INTEGER,null'),
            ('subtask_id', 'INTEGER,null')
        ],
        'AiCpuDataMap': [
            ('stream_id', 'INTEGER,null'),
            ('task_id', 'INTEGER,null'),
            ('sys_start', 'INTEGER, null'),
            ('sys_end', 'INTEGER, null'),
            ('node_name', 'TEXT, null'),
            ('compute_time', 'REAL, null'),
            ('memcpy_time', 'REAL, null'),
            ('task_time', 'REAL, null'),
            ('dispatch_time', 'REAL, null'),
            ('total_time', 'REAL, null')
        ],
        'AiCpuFromTsMap': [
            ('stream_id', 'INTEGER,null'),
            ('task_id', 'INTEGER,null'),
            ('sys_start', 'INTEGER, null'),
            ('sys_end', 'INTEGER, null')
        ],
        'AiCpuDPMap': [
            ('timestamp', 'TEXT,null'),
            ('action', 'TEXT,null'),
            ('source', 'TEXT, null'),
            ('buffer_size', 'INTEGER, null')
        ],
        'CpuInfoMap': [
            ('cpu_num', 'INTEGER, null'),
            ('clk_jiffies', 'INTEGER, null')
        ],
        'ProcessUsageMap': [
            ('timestamp', 'NUMERIC,null'),
            ('uptime', 'TEXT,null'),
            ('pid', 'INTEGER, null'),
            ('tid', 'INTEGER, null'),
            ('jiffies', 'INTEGER, null'),
            ('cpu_no', 'TEXT,null'),
            ('usage', 'REAL,null')
        ],
        'CpuUsageMap': [
            ('start_time', 'NUMERIC,null'),
            ('end_time', 'NUMERIC,null'),
            ('cpu_no', 'TEXT,null'),
            ('usage', 'REAL,null')
        ],
        'MemUsageMap': [
            ('start_time', 'NUMERIC,null'),
            ('end_time', 'NUMERIC,null'),
            ('usage', 'REAL,null')
        ],
        'DiskUsageMap': [
            ('start_time', 'NUMERIC,null'),
            ('end_time', 'NUMERIC,null'),
            ('disk_read', 'REAL,null'),
            ('disk_write', 'REAL,null'),
            ('swap_in', 'TEXT,null'),
            ('usage', 'REAL,null')
        ],
        'NetworkUsageMap': [
            ('start_time', 'NUMERIC,null'),
            ('end_time', 'NUMERIC,null'),
            ('usage', 'REAL,null'),
            ('speed', 'REAL,null')
        ],
        'SyscallMap': [
            ('runtime_comm', 'TEXT,null'),
            ('runtime_pid', 'INTEGER,null'),
            ('runtime_tid', 'INTEGER,null'),
            ('runtime_api_name', 'TEXT,null'),
            ('runtime_start_time', 'REAL,null'),
            ('runtime_duration', 'REAL,null'),
            ('runtime_end_time', 'REAL,null'),
            ('runtime_trans_start', 'REAL,null'),
            ('runtime_trans_end', 'REAL,null')
        ],
        'HwtsTaskMap': [
            ('task_type', 'INTEGER,null'),
            ('stream_id', 'INTEGER,null'),
            ('task_id', 'INTEGER,null'),
            ('sys_counter', 'INTEGER,null'),
            ('log_type', 'INTEGER,null')
        ],
        'HwtsTaskTimeMap': [
            ('stream_id', 'INTEGER,null'),
            ('task_id', 'INTEGER,null'),
            ('running', 'INTEGER,null'),
            ('complete', 'INTEGER,null'),
            ('task_type', 'text,null'),
            ('index_id', 'INTEGER,null'),
            ('model_id', 'INTEGER,null'),
        ],
        'HwtsIterMap': [
            ('iter_id', 'INTEGER,null'),
            ('model_id', 'INTEGER,null'),
            ('index_id', 'INTEGER,null'),
            ('task_count', 'INTEGER,null'),
            ('task_offset', 'INTEGER,null'),
            ('ai_core_num', 'INTEGER,null'),
            ('ai_core_offset', 'INTEGER,null')
        ],
        'HwtsBatchMap': [
            ('stream_id', 'INTEGER,null'),
            ('task_id', 'INTEGER,null'),
            ('batch_id', 'INTEGER,null'),
            ('iter_id', 'INTEGER,null'),
            ('start_time', 'REAL,null'),
            ('end_time', 'REAL,null'),
            ('is_ai_core', 'INTEGER,null')
        ],
        'GeMergeMap': [
            ('model_id', 'INTEGER,null'),
            ('op_name', 'TEXT,null'),
            ('op_type', 'TEXT,null'),
            ('task_type', 'TEXT,null'),
            ('task_id', 'INTEGER,null'),
            ('stream_id', 'INTEGER,null'),
            ('batch_id', 'INTEGER,null'),
            ('context_id', 'INTEGER,null')
        ],
        'RtsTaskMap': [
            ('task_id', 'INTEGER,null'),
            ('stream_id', 'INTEGER,null'),
            ('start_time', 'INTEGER,null'),
            ('duration', 'INTEGER,null'),
            ('task_type', 'TEXT,null'),
            ('index_id', 'INTEGER, null'),
            ('model_id', 'INTEGER,null'),
            ('batch_id', 'INTEGER,null'),
            ('subtask_id', 'INTEGER,null')
        ],
        'OpReportMap': [
            ('model_name', 'TEXT,null'),
            ('op_type', 'TEXT,null'),
            ('core_type', 'TEXT,null'),
            ('occurrences', 'TEXT,null'),
            ('total_time', 'REAL,null'),
            ('min', 'REAL,null'),
            ('avg', 'REAL,null'),
            ('max', 'REAL,null'),
            ('ratio', 'TEXT,null')
        ],
        'AcsqTaskMap': [
            ('stream_id', 'INTEGER,null'),
            ('task_id', 'INTEGER,null'),
            ('acc_id', 'INTEGER,null'),
            ('task_type', 'TEXT,null'),
            ('start_time', 'INTEGER,null'),
            ('end_time', 'INTEGER,null'),
            ('task_time', 'INTEGER,null')
        ],
        'AcsqTaskTimeMap': [
            ('task_id', 'INTEGER,null'),
            ('stream_id', 'INTEGER,null'),
            ('start_time', 'INTEGER,null'),
            ('task_time', 'INTEGER,null'),
            ('task_type', 'TEXT,null'),
            ('index_id', 'INTEGER,null'),
            ('model_id', 'INTEGER,null')
        ],
        'FftsLogMap': [
            ('stream_id', 'INTEGER,null'),
            ('task_id', 'INTEGER,null'),
            ('subtask_id', 'INTEGER,null'),
            ('thread_id', 'TEXT,null'),
            ('subtask_type', 'INTEGER,null'),
            ('ffts_type', 'INTEGER,null'),
            ('task_type', 'TEXT,null'),
            ('task_time', 'INTEGER,null')
        ],
        'SubtaskTimeMap': [
            ('subtask_id', 'INTEGER,null'),
            ('task_id', 'INTEGER,null'),
            ('stream_id', 'INTEGER,null'),
            ('subtask_type', 'text,null'),
            ('ffts_type', 'INTEGER,null'),
            ('start_time', 'NUMERIC,null'),
            ('end_time', 'NUMERIC,null'),
            ('dur_time', 'NUMERIC,null'),
            ('thread_id', 'INTEGER,null'),
        ],
        'StarsTaskTimeMap': [
            ('context_id', 'INTEGER, null'),
            ('task_id', 'INTEGER, null'),
            ('stream_id', 'INTEGER, null'),
            ('start_time', 'INTEGER,null'),
            ('duration_time', 'INTEGER, null'),
            ('wait_time', 'INTEGER, null'),
            ('task_type', 'INTEGER,null')
        ],
        'L2CacheParseMap': [
            ('task_type', 'INTEGER,null'),
            ('stream_id', 'INTEGER,null'),
            ('task_id', 'INTEGER,null'),
            ('event_lists', 'TEXT,null')
        ],
        'L2CacheSummaryMap': [
            ('task_type', 'INTEGER,null'),
            ('stream_id', 'INTEGER,null'),
            ('task_id', 'INTEGER,null'),
            ('hit_rate', 'REAL'),
            ('victim_rate', 'REAL')
        ],
        'BlockLogMap': [
            ('stream_id', 'NUMERIC,null'),
            ('task_id', 'NUMERIC,null'),
            ('block_id', 'NUMERIC,null'),
            ('task_type', 'TEXT,null'),
            ('start_time', 'NUMERIC,null'),
            ('end_time', 'NUMERIC,null'),
            ('task_time', 'NUMERIC,null'),
            ('core_type', 'NUMERIC,null'),
            ('core_id', 'NUMERIC,null')
        ],
        'HCCLTaskSingleDeviceMap': [
            ('model_id', 'INTEGER, null'),
            ('index_id', 'INTEGER, null'),
            ('op_name', 'TEXT, null'),
            ('iteration', 'INTEGER, null'),
            ('hccl_name', 'TEXT, null'),
            ('group_name', 'TEXT, null'),
            ('first_timestamp', 'NUMERIC, null'),
            ('plane_id', 'INTEGER, null'),
            ('timestamp', 'NUMERIC, null'),
            ('duration', 'REAL, null'),
            ('is_dynamic', 'REAL, null'),
            ('task_type', 'TEXT, null'),
            ('op_type', 'TEXT, null'),
            ('connection_id', 'INTEGER, null'),
            ('is_master', 'INTEGER, null'),
            ('stream_id', 'INTEGER, null'),
            ('task_id', 'INTEGER, null'),
            ('duration_estimated', 'INTEGER, null'),
            ('local_rank', 'INTEGER, null'),
            ('remote_rank', 'INTEGER, null'),
            ('transport_type', 'TEXT, null'),
            ('size', 'INTEGER, null'),
            ('data_type', 'TEXT, null'),
            ('link_type', 'TEXT, null'),
            ('bandwidth', 'REAL,null'),
            ('context_id', 'INTEGER, null'),
            ('notify_id', 'TEXT, null'),
            ('batch_id', 'INTEGER, null'),
            ('rdma_type', 'TEXT', 'null'),
        ],
        'HCCLOpSingleDeviceMap': [
            ('model_id', 'INTEGER, null'),
            ('op_name', 'TEXT, null'),
            ('task_type', 'TEXT, null'),
            ('op_type', 'TEXT, null'),
            ('timestamp', 'NUMERIC, null'),
            ('relay', 'INTEGER, null'),
            ('retry', 'INTEGER, null'),
            ('data_type', 'TEXT, null'),
            ('alg_type', 'TEXT, null'),
            ('count', 'NUMERIC, null'),
            ('group_name', 'TEXT, null'),
            ('connection_id', 'INTEGER, null'),
        ],
        'HCCLOPMap': [
            ('device_id', 'INTEGER, null'),
            ('model_id', 'INTEGER, null'),
            ('index_id', 'INTEGER, null'),
            ('thread_id', 'INTEGER, null'),
            ('op_name', 'TEXT, null'),
            ('task_type', 'TEXT, null'),
            ('op_type', 'TEXT, null'),
            ('begin', 'REAL, null'),
            ('end', 'REAL, null'),
            ('is_dynamic', 'TEXT, null'),
            ('connection_id', 'INTEGER, null'),
            ('kfc_connection_id', 'INTEGER, null'),
            ('relay', 'INTEGER, null'),
            ('retry', 'INTEGER, null'),
            ('data_type', 'TEXT, null'),
            ('alg_type', 'TEXT, null'),
            ('count', 'NUMERIC, null'),
            ('group_name', 'TEXT, null'),
        ],
        'HCCLTaskMap': [
            ('model_id', 'INTEGER, null'),
            ('index_id', 'INTEGER, null'),
            ('name', 'TEXT, null'),
            ('group_name', 'TEXT, null'),
            ('plane_id', 'INTEGER, null'),
            ('timestamp', 'NUMERIC, null'),
            ('duration', 'REAL, null'),
            ('stream_id', 'INTEGER, null'),
            ('task_id', 'INTEGER, null'),
            ('context_id', 'INTEGER, null'),
            ('batch_id', 'INTEGER, null'),
            ('device_id', 'INTEGER, null'),
            ('is_master', 'INTEGER, null'),
            ('local_rank', 'INTEGER, null'),
            ('remote_rank', 'INTEGER, null'),
            ('transport_type', 'TEXT, null'),
            ('size', 'REAL, null'),
            ('data_type', 'TEXT, null'),
            ('link_type', 'TEXT, null'),
            ('notify_id', 'TEXT, null'),
            ('rdma_type', 'TEXT', 'null'),
            ('thread_id', 'INTEGER, null'),
        ],
        'MsprofTxMap': [
            ('pid', 'INTEGER, null'),
            ('tid', 'INTEGER, null'),
            ('category', 'INTEGER, null'),
            ('event_type', 'TEXT, null'),
            ('payload_type', 'INTEGER, null'),
            ('payload_value', 'INTEGER, null'),
            ('start_time', 'INTEGER, null'),
            ('end_time', 'INTEGER, null'),
            ('message_type', 'INTEGER, null'),
            ('message', 'TEXT, null')
        ],
        'MsprofTxExMap': [
            ('pid', 'INTEGER, null'),
            ('tid', 'INTEGER, null'),
            ('event_type', 'TEXT, null'),
            ('start_time', 'INTEGER, null'),
            ('end_time', 'INTEGER, null'),
            ('mark_id', 'INTEGER, null'),
            ('domain', 'TEXT', 'null'),
            ('message', 'TEXT, null')
        ],
        'SioMap': [
            ('acc_id', 'INTEGER, null'),
            ('req_rx', 'NUMERIC, null'),
            ('rsp_rx', 'NUMERIC, null'),
            ('snp_rx', 'NUMERIC, null'),
            ('dat_rx', 'NUMERIC, null'),
            ('req_tx', 'NUMERIC, null'),
            ('rsp_tx', 'NUMERIC, null'),
            ('snp_tx', 'NUMERIC, null'),
            ('dat_tx', 'NUMERIC, null'),
            ('timestamp', 'NUMERIC, null')
        ],
        'InterSocMap': [
            ('l2_buffer_bw_level', 'INTEGER, null'),
            ('mata_bw_level', 'INTEGER, null'),
            ('sys_time', 'REAL,null')
        ],
        'AccPmuMap': [
            ('acc_id', 'INTEGER,null'),
            ('read_bandwidth', 'INTEGER, null'),
            ('write_bandwidth', 'INTEGER, null'),
            ('read_ost', 'INTEGER, null'),
            ('write_ost', 'INTEGER, null'),
            ('timestamp', 'NUMERIC, null')
        ],
        'ModelWithQMap': [
            ('index_id', 'INTEGER, null'),
            ('model_id', 'INTEGER, null'),
            ('timestamp', 'NUMERIC, null'),
            ('tag_id', 'INTEGER, null'),
            ('event_id', 'INTEGER, null')
        ],
        'PaLinkInfoMap': [
            ('pa_link_id', 'INTEGER, null'),
            ('pa_link_traffic_monit_rx', 'TEXT, null'),
            ('pa_link_traffic_monit_tx', 'TEXT,null'),
            ('sys_time', 'TEXT,null')
        ],
        'PcieInfoMap': [
            ('pcie_id', 'INTEGER, null'),
            ('pcie_write_bandwidth', 'INTEGER, null'),
            ('pcie_read_bandwidth', 'INTEGER, null'),
            ('sys_time', 'INTEGER,null')
        ],
        'PcieInfoV6Map': [
            ('die_id', 'INTEGER, null'),
            ('sys_time', 'INTEGER, null'),
            ('pcie_write_bandwidth', 'NUMERIC, null'),
            ('pcie_read_bandwidth', 'NUMERIC, null')
        ],
        'LowPowerMap': [
            ('timestamp', 'NUMERIC, null'),
            ('die_id', 'NUMERIC, null'),
            ('data0_hard', 'NUMERIC, null'),
            ('data1_hard', 'NUMERIC, null'),
            ('data2_hard', 'NUMERIC, null'),
            ('data3_hard', 'NUMERIC, null'),
            ('data4_hard', 'NUMERIC, null'),
            ('data5_hard', 'NUMERIC, null'),
            ('data6_hard', 'NUMERIC, null'),
            ('data7_hard', 'NUMERIC, null'),
            ('data8_hard', 'NUMERIC, null'),
            ('data9_hard', 'NUMERIC, null'),
            ('data0_soft', 'NUMERIC, null'),
            ('data1_soft', 'NUMERIC, null'),
            ('data2_soft', 'NUMERIC, null'),
            ('data3_soft', 'NUMERIC, null'),
            ('data4_soft', 'NUMERIC, null'),
            ('data5_soft', 'NUMERIC, null'),
            ('data6_soft', 'NUMERIC, null'),
            ('data7_soft', 'NUMERIC, null'),
            ('data8_soft', 'NUMERIC, null'),
            ('data9_soft', 'NUMERIC, null')
        ],
        'MonitorFlowMap': [
            ('stat_rcmd_num', 'INTEGER, null'),
            ('stat_wcmd_num', 'INTEGER, null'),
            ('stat_rlat_raw', 'INTEGER, null'),
            ('stat_wlat_raw', 'INTEGER, null'),
            ('stat_flux_rd', 'INTEGER, null'),
            ('stat_flux_wr', 'INTEGER, null'),
            ('stat_flux_rd_l2', 'INTEGER, null'),
            ('stat_flux_wr_l2', 'INTEGER, null'),
            ('timestamp', 'NUMERIC, null'),
            ('l2_cache_hit', 'INTEGER, null'),
            ('core_id', 'INTEGER, null'),
            ('group_id', 'INTEGER, null'),
            ('core_type', 'TEXT, null')
        ],
        'MonitorCyclesMap': [
            ('vector_cycles', 'INTEGER, null'),
            ('scalar_cycles', 'INTEGER, null'),
            ('cube_cycles', 'INTEGER, null'),
            ('lsu1_cycles', 'INTEGER, null'),
            ('lsu2_cycles', 'INTEGER, null'),
            ('lsu3_cycles', 'INTEGER, null'),
            ('timestamp', 'NUMERIC, null'),
            ('core_id', 'INTEGER, null'),
            ('group_id', 'INTEGER, null'),
            ('core_type', 'TEXT, null')
        ],
        'BiuFlowMap': [
            ('timestamp', 'NUMERIC, null'),
            ('flow', 'INTEGER, null'),
            ('flow_type', 'TEXT, null'),
            ('unit_name', 'TEXT, null'),
            ('pid', 'INTEGER, null'),
            ('tid', 'INTEGER, null'),
            ('interval_start', 'INTEGER, null')
        ],
        'BiuCyclesMap': [
            ('timestamp', 'NUMERIC, null'),
            ('duration', 'INTEGER, null'),
            ('cycle_type', 'TEXT, null'),
            ('unit_name', 'TEXT, null'),
            ('cycle_num', 'INTEGER, null'),
            ('ratio', 'REAL, null'),
            ('pid', 'INTEGER, null'),
            ('tid', 'INTEGER, null'),
            ('interval_start', 'INTEGER, null')
        ],
        'TaskTypeMap': [
            ('timestamp', 'NUMERIC, null'),
            ('stream_id', 'INTEGER, null'),
            ('task_id', 'INTEGER, null'),
            ('task_type', 'TEXT, null'),
            ('task_state', 'INTEGER, null')
        ],
        'GeSummaryMap': [
            ('model_id', 'INTEGER,null'),
            ('batch_id', 'INTEGER,null'),
            ('task_id', 'INTEGER,null'),
            ('stream_id', 'INTEGER,null'),
            ('op_name', 'TEXT,null'),
            ('op_type', 'TEXT,null'),
            ('op_state', 'TEXT,null'),
            ('block_num', 'INTEGER,null'),
            ('mix_block_num', 'INTEGER,null'),
            ('task_type', 'TEXT,null'),
            ('tensor_num', 'INTEGER,null'),
            ('input_formats', 'TEXT,null'),
            ('input_data_types', 'TEXT,null'),
            ('input_shapes', 'TEXT,null'),
            ('output_formats', 'TEXT,null'),
            ('output_data_types', 'TEXT,null'),
            ('output_shapes', 'TEXT,null'),
            ('timestamp', 'NUMERIC,null'),
            ('index_id', 'INTEGER,null'),
            ('context_id', 'INTEGER,null'),
            ('op_flag', 'TEXT,null')
        ],
        'TimeMap': [
            ('device_id', 'INTEGER,null'),
            ('dev_mon', 'INTEGER,null'),
            ('dev_wall', 'INTEGER,null'),
            ('dev_cntvct', 'INTEGER,null'),
            ('host_mon', 'INTEGER,null'),
            ('host_wall', 'INTEGER,null')
        ],
        'ClusterRankMap': [
            ('job_info', 'TEXT,null'),
            ('device_id', 'INTEGER,null'),
            ('collection_time', 'TEXT,null'),
            ('rank_id', 'INTEGER,null'),
            ('dir_name', 'TEXT,null')
        ],
        'ClusterStepTraceMap': [
            ('device_id', 'INTEGER,null'),
            ('model_id', 'INTEGER,null'),
            ('iteration_id', 'INTEGER,null'),
            ('fp_start', 'REAL,null'),
            ('bp_end', 'REAL,null'),
            ('iteration_end', 'REAL,null'),
            ('iteration_time', 'REAL,null'),
            ('fp_bp_time', 'REAL,null'),
            ('grad_refresh_bound', 'REAL,null'),
            ('data_aug_bound', 'REAL,null'),
            ('ge_tag', 'INTEGER,null')
        ],
        'DataQueueMap': [
            ('node_name', 'TEXT,null'),
            ('queue_size', 'INTEGER,null'),
            ('start_time', 'REAL,null'),
            ('end_time', 'REAL,null'),
            ('duration', 'REAL,null')
        ],
        'AllReduceMap': [
            ('device_id', 'INTEGER,null'),
            ('model_id', 'INTEGER,null'),
            ('index_id', 'INTEGER,null'),
            ('iteration_end', 'INTEGER,null'),
            ('all_reduce_start', 'INTEGER,null'),
            ('all_reduce_end', 'INTEGER,null')
        ],
        'HostQueueMap': [
            ('type', 'INTEGER,null'),
            ('extra_info', 'INTEGER,null'),
            ('index_id', 'INTEGER,null'),
            ('value', 'INTEGER,null'),
            ('mode', 'INTEGER,null')
        ],
        'HcclOperatorExeMap': [
            ('model_id', 'INTEGER,null'),
            ('index_id', 'INTEGER,null'),
            ('op_name', 'TEXT,null'),
            ('op_type', 'TEXT,null'),
            ('start_time', 'REAL,null'),
            ('end_time', 'REAL,null')
        ],
        'ParallelStrategyMap': [
            ('ai_frame_type', 'TEXT,null'),
            ('stage_num', 'INTEGER,null'),
            ('rankId', 'INTEGER,null'),
            ('stageId', 'INTEGER,null'),
            ('parallelType', 'TEXT,null'),
            ('stageDevices', 'TEXT,null'),
            ('parallel_mode', 'TEXT,null')
        ],
        'HcclOperatorOverlapMap': [
            ('model_id', 'INTEGER,null'),
            ('index_id', 'INTEGER,null'),
            ('op_name', 'TEXT,null'),
            ('op_type', 'TEXT,null'),
            ('start_time', 'REAL,null'),
            ('end_time', 'REAL,null'),
            ('overlap_time', 'REAL,null')
        ],
        'ComputationTimeMap': [
            ('model_id', 'INTEGER,null'),
            ('index_id', 'INTEGER,null'),
            ('step_time', 'REAL,null'),
            ('computation_time', 'REAL,null')
        ],
        'ClusterDataParallelMap': [
            ('rank_id', 'INTEGER,null'),
            ('device_id', 'INTEGER,null'),
            ('model_id', 'INTEGER,null'),
            ('iteration_id', 'INTEGER,null'),
            ('step_time', 'REAL,null'),
            ('computation_time', 'REAL,null'),
            ('pure_communication_time', 'REAL,null'),
            ('communication_time', 'REAL,null'),
            ('interval_of_communication_time', 'REAL,null'),
            ('hccl_op_num', 'INTEGER,null')
        ],
        'ClusterModelParallelMap': [
            ('rank_id', 'INTEGER,null'),
            ('device_id', 'INTEGER,null'),
            ('model_id', 'INTEGER,null'),
            ('iteration_id', 'INTEGER,null'),
            ('step_time', 'REAL,null'),
            ('computation_time', 'REAL,null'),
            ('pure_communication_time', 'REAL,null'),
            ('communication_time', 'REAL,null')
        ],
        'ClusterPipelineParallelMap': [
            ('rank_id', 'INTEGER,null'),
            ('device_id', 'INTEGER,null'),
            ('model_id', 'INTEGER,null'),
            ('iteration_id', 'INTEGER,null'),
            ('step_time', 'REAL,null'),
            ('computation_time', 'REAL,null'),
            ('pure_communication_time', 'REAL,null'),
            ('communication_time', 'REAL,null'),
            ('pure_communication_time_only_revice', 'REAL,null'),
            ('pure_communication_time_except_revice', 'REAL,null')
        ],
        'ClusterParallelStrategyMap': [
            ('ai_frame_type', 'TEXT,null'),
            ('stage_num', 'INTEGER,null'),
            ('rankId', 'INTEGER,null'),
            ('stageId', 'INTEGER,null'),
            ('parallelType', 'TEXT,null'),
            ('stageDevices', 'TEXT,null'),
            ('parallel_mode', 'TEXT,null')
        ],
        'NpuMemMap': [
            ('event', 'TEXT,null'),
            ('ddr', 'INTEGER,null'),
            ('hbm', 'INTEGER,null'),
            ('timestamp', 'NUMERIC,null'),
            ('memory', 'INTEGER,null')
        ],
        'TorchAclRelationMap': [
            ('op_name', 'TEXT,null'),
            ('mark_time', 'INTEGER,null'),
            ('acl_start_time', 'INTEGER,null'),
            ('acl_end_time', 'INTEGER,null'),
            ('acl_tid', 'INTEGER,null'),
            ('acl_compile_time', 'INTEGER,null'),
            ('torch_op_start_time', 'INTEGER,null'),
            ('torch_op_tid', 'INTEGER,null'),
            ('torch_op_pid', 'INTEGER,null')
        ],
        'TorchNpuRelationMap': [
            ('torch_op_start_time', 'INTEGER,null'),
            ('torch_op_tid', 'INTEGER,null'),
            ('torch_op_pid', 'INTEGER,null'),
            ('op_name', 'TEXT,null'),
            ('acl_start_time', 'INTEGER,null'),
            ('acl_end_time', 'INTEGER,null'),
            ('acl_tid', 'INTEGER,null'),
            ('acl_compile_time', 'INTEGER,null'),
            ('stream_id', 'INTEGER,null'),
            ('task_id', 'INTEGER,null'),
            ('batch_id', 'INTEGER,null'),
            ('context_id', 'INTEGER,null'),
            ('kernel_name', 'TEXT,null'),
            ('kernel_type', 'TEXT,null'),
            ('is_main_kernel', 'INTEGER,null')
        ],
        'FreqParseMap': [
            ('syscnt', 'INTEGER,null'),
            ('freq', 'INTEGER,null'),
        ],
        'ApiDataMap': [
            ('struct_type', 'TEXT,null'),
            ('id', 'TEXT,null'),
            ('level', 'TEXT,null'),
            ('thread_id', 'INTEGER,null'),
            ('item_id', 'TEXT,null'),
            ('start', 'INTEGER,null'),
            ('end', 'INTEGER,null'),
            ('connection_id', 'INTEGER,null'),
        ],
        'EventDataMap': [
            ('struct_type', 'TEXT,null'),
            ('level', 'TEXT,null'),
            ('thread_id', 'INTEGER,null'),
            ('item_id', 'INTEGER,null'),
            ('request_id', 'INTEGER,null'),
            ('timestamp', 'NUMERIC,null'),
            ('connection_id', 'INTEGER,null'),
        ],
        'TaskTrackMap': [
            ('device_id', 'INTEGER,null'),
            ('timestamp', 'NUMERIC,null'),
            ('task_type', 'TEXT,null'),
            ('stream_id', 'INTEGER,null'),
            ('task_id', 'INTEGER,null'),
            ('thread_id', 'INTEGER,null'),
            ('batch_id', 'INTEGER,null'),
            ('struct_type', 'TEXT,null'),
            ('level', 'TEXT,null'),
            ('data_len', 'INTEGER,null'),
            ('kernel_name', 'TEXT,null'),
        ],
        'RuntimeOpInfoMap': [
            ('level', 'TEXT,null'),
            ('struct_type', 'TEXT,null'),
            ('thread_id', 'INTEGER,null'),
            ('timestamp', 'NUMERIC,null'),
            ('device_id', 'INTEGER,null'),
            ('model_id', 'INTEGER,null'),
            ('stream_id', 'INTEGER,null'),
            ('task_id', 'INTEGER,null'),
            ('op_name', 'TEXT,null'),
            ('task_type', 'TEXT,null'),
            ('op_type', 'TEXT,null'),
            ('hash_id', 'TEXT,null'),
            ('block_num', 'INTEGER,null'),
            ('mix_block_num', 'INTEGER,null'),
            ('op_flag', 'INTEGER,null'),
            ('is_dynamic', 'INTEGER,null'),
            ('tensor_num', 'INTEGER,null'),
            ('input_formats', 'TEXT,null'),
            ('input_data_types', 'TEXT,null'),
            ('input_shapes', 'TEXT,null'),
            ('output_formats', 'TEXT,null'),
            ('output_data_types', 'TEXT,null'),
            ('output_shapes', 'TEXT,null'),
        ],
        'MemcpyInfoMap': [
            ('struct_type', 'TEXT,null'),
            ('level', 'TEXT,null'),
            ('thread_id', 'INTEGER,null'),
            ('data_len', 'INTEGER,null'),
            ('timestamp', 'NUMERIC,null'),
            ('data_size', 'INTEGER,null'),
            ('memcpy_direction', 'INTEGER,null'),
        ],
        'HcclInfoDataMap': [
            ('level', 'TEXT,null'),
            ('struct_type', 'TEXT,null'),
            ('thread_id', 'INTEGER,null'),
            ('data_len', 'INTEGER,null'),
            ('timestamp', 'NUMERIC,null'),
            ('op_name', 'INTEGER,null'),
            ('ccl_tag', 'TEXT,null'),
            ('group_name', 'TEXT,null'),
            ('local_rank', 'INTEGER,null'),
            ('remote_rank', 'INTEGER,null'),
            ('rank_size', 'INTEGER,null'),
            ('work_flow_mode', 'INTEGER,null'),
            ('plane_id', 'INTEGER,null'),
            ('context_id', 'INTEGER,null'),
            ('notify_id', 'TEXT,null'),
            ('stage', 'TEXT,null'),
            ('role', 'TEXT,null'),
            ('duration_estimated', 'INTEGER,null'),
            ('src_addr', 'TEXT,null'),
            ('dst_addr', 'TEXT,null'),
            ('size', 'INTEGER,null'),
            ('op_type', 'TEXT,null'),
            ('data_type', 'TEXT,null'),
            ('link_type', 'TEXT,null'),
            ('transport_type', 'TEXT,null'),
            ('rdma_type', 'TEXT,null'),
        ],
        'MultiThreadDataMap': [
            ('type', 'TEXT,null'),
            ('level', 'TEXT,null'),
            ('thread_id', 'INTEGER,null'),
            ('data_len', 'INTEGER,null'),
            ('timestamp', 'NUMERIC,null'),
            ('thread_num', 'INTEGER,null'),
            ('sub_thread_id', 'TEXT,null'),
        ],
        'TensorInfoV2Map': [
            ('level', 'TEXT,null'),
            ('struct_type', 'TEXT,null'),
            ('thread_id', 'INTEGER,null'),
            ('timestamp', 'NUMERIC,null'),
            ('op_name', 'TEXT,null'),
            ('tensor_num', 'INTEGER,null'),
            ('input_formats', 'TEXT,null'),
            ('input_data_types', 'TEXT,null'),
            ('input_shapes', 'TEXT,null'),
            ('output_formats', 'TEXT,null'),
            ('output_data_types', 'TEXT,null'),
            ('output_shapes', 'TEXT,null'),
        ],
        'NodeBasicInfoMap': [
            ('level', 'TEXT,null'),
            ('struct_type', 'TEXT,null'),
            ('thread_id', 'INTEGER,null'),
            ('timestamp', 'NUMERIC,null'),
            ('op_name', 'TEXT,null'),
            ('task_type', 'TEXT,null'),
            ('op_type', 'TEXT,null'),
            ('block_num', 'INTEGER,null'),
            ('mix_block_num', 'INTEGER,null'),
            ('op_flag', 'INTEGER,null'),
            ('is_dynamic', 'INTEGER,null'),
        ],
        'NodeAttrInfoMap': [
            ('level', 'TEXT,null'),
            ('struct_type', 'TEXT,null'),
            ('thread_id', 'INTEGER,null'),
            ('timestamp', 'NUMERIC,null'),
            ('op_name', 'TEXT,null'),
            ('hashid', 'TEXT,null'),
        ],
        'GraphIdMapMap': [
            ('level', 'TEXT,null'),
            ('struct_type', 'TEXT,null'),
            ('thread_id', 'INTEGER,null'),
            ('timestamp', 'NUMERIC,null'),
            ('model_name', 'TEXT,null'),
            ('graph_id', 'INTEGER,null'),
        ],
        'FusionOPInfoMap': [
            ('level', 'TEXT,null'),
            ('struct_type', 'TEXT,null'),
            ('thread_id', 'INTEGER,null'),
            ('timestamp', 'NUMERIC,null'),
            ('op_name', 'TEXT,null'),
            ('fusion_op_num', 'INTEGER,null'),
            ('memory_input', 'TEXT,null'),
            ('memory_output', 'TEXT,null'),
            ('memory_weight', 'TEXT,null'),
            ('memory_workspace', 'TEXT,null'),
            ('memory_total', 'TEXT,null'),
            ('fusion_op_names', 'TEXT,null'),
        ],
        'MemoryApplicationMap': [
            ('level', 'TEXT,null'),
            ('type', 'TEXT,null'),
            ('thread_id', 'INTEGER,null'),
            ('timestamp', 'NUMERIC,null'),
            ('op_name', 'TEXT,null'),
            ('ptr', 'TEXT,null'),
            ('memory_size', 'TEXT,null'),
            ('total_memory_size', 'TEXT,null'),
            ('used_memory_size', 'TEXT,null'),
            ('device_type', 'TEXT,null'),
            ('device_id', 'INTEGER,null'),
        ],
        'CtxIdMap': [
            ('level', 'TEXT,null'),
            ('struct_type', 'TEXT,null'),
            ('thread_id', 'INTEGER,null'),
            ('timestamp', 'NUMERIC,null'),
            ('op_name', 'TEXT,null'),
            ('ctx_id_num', 'INTEGER,null'),
            ('ctx_id', 'TEXT,null'),
        ],
        'StaticOpMemMap': [
            ('op_name', 'TEXT,null'),
            ('model_name', 'TEXT,null'),
            ('graph_id', 'NUMERIC,null'),
            ('node_index_start', 'NUMERIC,null'),
            ('node_index_end', 'NUMERIC,null'),
            ('op_mem_size', 'NUMERIC,null'),
        ],
        'V5TaskMap': [
            ('model_id', 'INTEGER,null'),
            ('stream_id', 'INTEGER,null'),
            ('task_id', 'INTEGER,null'),
            ('task_type', 'TEXT,null'),
            ('start_time', 'NUMERIC,null'),
            ('end_time', 'NUMERIC,null'),
            ('duration', 'NUMERIC,null'),
            ('total_cycle', 'NUMERIC,null'),
            ('block_num', 'INTEGER,null'),
            ('pmu0', 'NUMERIC,null'),
            ('pmu1', 'NUMERIC,null'),
            ('pmu2', 'NUMERIC,null'),
            ('pmu3', 'NUMERIC,null'),
            ('pmu4', 'NUMERIC,null'),
            ('pmu5', 'NUMERIC,null'),
            ('pmu6', 'NUMERIC,null'),
            ('pmu7', 'NUMERIC,null'),
            ('pmu8', 'NUMERIC,null'),
            ('pmu9', 'NUMERIC,null')
        ],
        'HostTaskMap': [
            ('model_id', 'INTEGER,null'),
            ('request_id', 'INTEGER,null'),
            ('stream_id', 'INTEGER,null'),
            ('task_id', 'INTEGER,null'),
            ('context_ids', 'TEXT,null'),
            ('batch_id', 'INTEGER,null'),
            ('task_type', 'TEXT,null'),
            ('kernel_name', 'TEXT,null'),
            ('device_id', 'INTEGER,null'),
            ('timestamp', 'NUMERIC,null'),
            ('connection_id', 'INTEGER,null'),
        ],
        'DPUTaskTrackMap': [
            ('dpu_device_id', 'INTEGER,null'),
            ('thread_id', 'INTEGER,null'),
            ('start_time', 'NUMERIC,null'),
            ('end_time', 'NUMERIC,null'),
            ('task_type', 'TEXT,null'),
            ('stream_id', 'INTEGER,null'),
            ('task_id', 'INTEGER,null'),
            ('kernel_name', 'TEXT,null'),
        ],
        'DPUHcclTrackMap': [
            ('npu_device_id', 'INTEGER,null'),
            ('dpu_device_id', 'INTEGER,null'),
            ('thread_id', 'INTEGER,null'),
            ('start_time', 'NUMERIC,null'),
            ('end_time', 'NUMERIC,null'),
            ('op_name', 'TEXT,null'),
            ('group_name', 'TEXT,null'),
            ('local_rank', 'INTEGER,null'),
            ('remote_rank', 'INTEGER,null'),
            ('rank_size', 'INTEGER,null'),
            ('duration_estimated', 'NUMERIC,null'),
            ('src_addr', 'TEXT,null'),
            ('dst_addr', 'TEXT,null'),
            ('data_size', 'INTEGER,null'),
            ('stream_id', 'INTEGER,null'),
            ('task_id', 'INTEGER,null'),
            ('aicpu_task_id', 'INTEGER,null'),
            ('plane_id', 'INTEGER,null'),
            ('op_type', 'TEXT,null'),
            ('data_type', 'TEXT,null'),
            ('link_type', 'TEXT,null'),
            ('transport_type', 'TEXT,null'),
            ('rdma_type', 'TEXT,null'),
            ('role', 'TEXT,null'),
            ('ccl_tag', 'TEXT,null'),
            ('notify_id', 'TEXT,null'),
            ('work_flow_mode', 'TEXT,null'),
            ('stage', 'TEXT,null')
        ],
        'AscendTaskMap': [
            ('model_id', 'INTEGER,null'),
            ('index_id', 'INTEGER,null'),
            ('stream_id', 'INTEGER,null'),
            ('task_id', 'INTEGER,null'),
            ('context_id', 'INTEGER,null'),
            ('batch_id', 'INTEGER,null'),
            ('start_time', 'NUMERIC,null'),
            ('duration', 'NUMERIC,null'),
            ('host_task_type', 'TEXT,null'),
            ('device_task_type', 'TEXT,null'),
            ('connection_id', 'INTEGER,null'),
        ],
        'NpuOpMemRawMap': [
            ('operator', 'TEXT,null'),
            ('addr', 'TEXT,null'),
            ('size', 'INTEGER,null'),
            ('timestamp', 'NUMERIC,null'),
            ('thread_id', 'INTEGER,null'),
            ('total_allocate_memory', 'INTEGER,null'),
            ('total_reserve_memory', 'INTEGER,null'),
            ('level', 'INTEGER,null'),
            ('type', 'INTEGER,null'),
            ('device_type', 'TEXT,null')
        ],
        'NpuOpMemMap': [
            ('operator', 'TEXT,null'),
            ('size', 'INTEGER,null'),
            ('allocation_time', 'NUMERIC,null'),
            ('release_time', 'NUMERIC,null'),
            ('duration', 'NUMERIC,null'),
            ('allocation_total_allocated', 'INTEGER,null'),
            ('allocation_total_reserved', 'INTEGER,null'),
            ('release_total_allocated', 'INTEGER,null'),
            ('release_total_reserved', 'INTEGER,null'),
            ('device_type', 'TEXT,null'),
            ('name', 'TEXT,null')
        ],
        'NpuOpMemRecMap': [
            ('component', 'TEXT,null'),
            ('timestamp', 'NUMERIC,null'),
            ('total_reserve_memory', 'INTEGER,null'),
            ('total_allocate_memory', 'INTEGER,null'),
            ('device_type', 'TEXT,null')
        ],
        'HcclOpReportMap': [
            ('op_type', 'TEXT,null'),
            ('occurrences', 'TEXT,null'),
            ('total_time', 'NUMERIC,null'),
            ('min', 'NUMERIC,null'),
            ('avg', 'NUMERIC,null'),
            ('max', 'NUMERIC,null'),
            ('ratio', 'TEXT,null')
        ],
        'HostTaskFlipMap': [
            ('stream_id', 'INTEGER,null'),
            ('timestamp', 'NUMERIC,null'),
            ('task_id', 'INTEGER,null'),
            ('flip_num', 'INTEGER,null'),
        ],
        'DeviceTaskFlipMap': [
            ('stream_id', 'INTEGER,null'),
            ('timestamp', 'NUMERIC,null'),
            ('task_id', 'INTEGER,null'),
            ('flip_num', 'INTEGER,null'),
        ],
        'NpuModuleMemMap': [
            ('module_id', 'INTEGER,null'),
            ('syscnt', 'NUMERIC,null'),  # syscnt: cycle count from host cpu
            ('total_size', 'INTEGER,null'),
            ('device_type', 'TEXT,null')
        ],
        'ModelNameMap': [
            ('model_id', 'INTEGER,null'),
            ('model_name', 'TEXT,null'),
        ],
        'CommAnalyzerTimeMap': [
            ('hccl_op_name', 'TEXT,null'),
            ('group_name', 'TEXT,null'),
            ('start_timestamp', 'NUMERIC,null'),
            ('elapse_time', 'NUMERIC,null'),
            ('transit_time', 'NUMERIC,null'),
            ('wait_time', 'NUMERIC,null'),
            ('synchronization_time', 'NUMERIC,null'),
            ('idle_time', 'NUMERIC,null'),
        ],
        'CommAnalyzerBandwidthMap': [
            ('hccl_op_name', 'TEXT,null'),
            ('group_name', 'TEXT,null'),
            ('transport_type', 'TEXT,null'),
            ('transit_size', 'NUMERIC,null'),
            ('transit_time', 'NUMERIC,null'),
            ('bandwidth', 'NUMERIC,null'),
            ('large_packet_ratio', 'NUMERIC,null'),
            ('package_size', 'NUMERIC,null'),
            ('count', 'NUMERIC,null'),
            ('total_duration', 'NUMERIC,null'),
        ],
        'CommAnalyzerMatrixMap': [
            ('hccl_op_name', 'TEXT,null'),
            ('group_name', 'TEXT,null'),
            ('src_rank', 'TEXT,null'),
            ('dst_rank', 'TEXT,null'),
            ('transport_type', 'TEXT,null'),
            ('transit_size', 'NUMERIC,null'),
            ('transit_time', 'NUMERIC,null'),
            ('bandwidth', 'NUMERIC,null'),
        ],
        'HcclOpInfoMap': [
            ('level', 'TEXT,null'),
            ('struct_type', 'TEXT,null'),
            ('thread_id', 'INTEGER,null'),
            ('timestamp', 'NUMERIC,null'),
            ('relay', 'INTEGER,null'),
            ('retry', 'INTEGER,null'),
            ('data_type', 'TEXT,null'),
            ('alg_type', 'TEXT,null'),
            ('count', 'NUMERIC,null'),
            ('group_name', 'TEXT,null')
        ],
        'DeviceHcclOpInfoMap': [
            ('timestamp', 'NUMERIC,null'),
            ('relay', 'INTEGER,null'),
            ('retry', 'INTEGER,null'),
            ('data_type', 'TEXT,null'),
            ('alg_type', 'TEXT,null'),
            ('count', 'NUMERIC,null'),
            ('group_name', 'TEXT,null'),
            ('stream_id', 'INTEGER,null'),
            ('task_id', 'INTEGER,null'),
            ('rank_size', 'INTEGER,null'),
            ('source', 'INTEGER,null'),
        ],
        'AicpuTaskFlipMap': [
            ('stream_id', 'INTEGER,null'),
            ('timestamp', 'NUMERIC,null'),
            ('task_id', 'INTEGER,null'),
            ('flip_num', 'INTEGER,null'),
        ],
        'AicpuMasterStreamHcclTaskMap': [
            ('timestamp', 'NUMERIC,null'),
            ('aicpu_stream_id', 'INTEGER,null'),
            ('aicpu_task_id', 'INTEGER,null'),
            ('stream_id', 'INTEGER,null'),
            ('task_id', 'INTEGER,null'),
            ('type', 'INTEGER,null'),
        ],
        'QosBwDataMap': [
            ('timestamp', 'NUMERIC,null'),
            ('die_id', 'NUMERIC,null'),
            ('bw1', 'NUMERIC,null'),
            ('bw2', 'NUMERIC,null'),
            ('bw3', 'NUMERIC,null'),
            ('bw4', 'NUMERIC,null'),
            ('bw5', 'NUMERIC,null'),
            ('bw6', 'NUMERIC,null'),
            ('bw7', 'NUMERIC,null'),
            ('bw8', 'NUMERIC,null'),
            ('bw9', 'NUMERIC,null'),
            ('bw10', 'NUMERIC,null')
        ],
        'Mc2CommInfoMap': [
            ('group_name', 'TEXT,null'),
            ('rank_size', 'INT,null'),
            ('rank_id', 'INT,null'),
            ('usr_rank_id', 'INT,null'),
            ('aicpu_kfc_stream_id', 'INT,null'),
            ('comm_stream_ids', 'TEXT,null'),
        ],
        'KfcCommTurnMap': [
            ('device_id', 'INT,null'),
            ('stream_id', 'INT,null'),
            ('task_id', 'INT,null'),
            ('comm_turn', 'INT,null'),
            ('current_turn', 'INT,null'),
            ('server_start_time', 'INT,null'),
            ('wait_msg_start_time', 'INT,null'),
            ('kfc_alg_exe_start_time', 'INT,null'),
            ('send_task_start_time', 'INT,null'),
            ('send_sqe_finish_time', 'INT,null'),
            ('rtsq_exe_end_time', 'INT,null'),
            ('server_end_time', 'INT,null'),
        ],
        'KfcComputeTurnMap': [
            ('device_id', 'INT,null'),
            ('stream_id', 'INT,null'),
            ('task_id', 'INT,null'),
            ('compute_turn', 'INT,null'),
            ('current_turn', 'INT,null'),
            ('wait_compute_start_time', 'INT,null'),
            ('compute_start_time', 'INT,null'),
            ('compute_exe_end_time', 'INT,null'),
        ],
        'KfcInfoMap': [
            ('timestamp', 'NUMERIC,null'),
            ('op_name', 'TEXT,null'),
            ('ccl_tag', 'TEXT,null'),
            ('group_name', 'TEXT,null'),
            ('local_rank', 'INTEGER,null'),
            ('remote_rank', 'INTEGER,null'),
            ('rank_size', 'INTEGER,null'),
            ('work_flow_mode', 'INT,null'),
            ('plane_id', 'INTEGER,null'),
            ('context_id', 'INTEGER,null'),
            ('notify_id', 'TEXT,null'),
            ('stage', 'TEXT,null'),
            ('role', 'TEXT,null'),
            ('duration_estimated', 'INTEGER,null'),
            ('src_addr', 'TEXT,null'),
            ('dst_addr', 'TEXT,null'),
            ('size', 'INTEGER,null'),
            ('op_type', 'TEXT,null'),
            ('data_type', 'TEXT,null'),
            ('link_type', 'TEXT,null'),
            ('transport_type', 'TEXT,null'),
            ('rdma_type', 'TEXT,null'),
            ('stream_id', 'INTEGER,null'),
            ('task_id', 'INTEGER,null'),
        ],
        'KfcOPMap': [
            ('model_id', 'INT,null'),
            ('index_id', 'INT,null'),
            ('op_name', 'TEXT,null'),
            ('timestamp', 'NUMERIC,null'),
            ('duration', 'NUMERIC,null'),
            ('group_name', 'TEXT,null'),
            ('connection_id', 'INTEGER,null'),
            ('op_type', 'TEXT,null'),
            ('relay', 'INTEGER,null'),
            ('retry', 'INTEGER,null'),
            ('data_type', 'TEXT,null'),
            ('alg_type', 'TEXT,null'),
            ('count', 'NUMERIC,null'),
            ('rank_size', 'INTEGER,null'),
            ('source', 'INTEGER,null'),
        ],
        'KfcTaskMap': [
            ('model_id', 'INTEGER,null'),
            ('index_id', 'INTEGER,null'),
            ('op_name', 'TEXT,null'),
            ('first_timestamp', 'NUMERIC,null'),
            ('iteration', 'INTEGER,null'),
            ('hccl_name', 'TEXT,null'),
            ('group_name', 'TEXT,null'),
            ('plane_id', 'INTEGER,null'),
            ('timestamp', 'NUMERIC,null'),
            ('duration', 'REAL,null'),
            ('is_master', 'INTEGER,null'),
            ('stream_id', 'INTEGER,null'),
            ('task_id', 'INTEGER,null'),
            ('duration_estimated', 'INTEGER,null'),
            ('local_rank', 'INTEGER,null'),
            ('remote_rank', 'INTEGER,null'),
            ('transport_type', 'TEXT,null'),
            ('size', 'INT,null'),
            ('data_type', 'TEXT,null'),
            ('link_type', 'TEXT,null'),
            ('bandwidth', 'REAL,null'),
            ('context_id', 'INTEGER,null'),
            ('notify_id', 'TEXT,null'),
            ('batch_id', 'INTEGER,null'),
            ('rdma_type', 'TEXT,null'),
            ('connection_id', 'INTEGER,null'),
            ('source', 'INTEGER,null'),
        ],
        'TsBlockNumMap': [
            ('timestamp', 'NUMERIC,null'),
            ('stream_id', 'INTEGER,null'),
            ('task_id', 'INTEGER,null'),
            ('block_num', 'INTEGER,null'),
        ],
        'UBBwDataMap': [
            ('device_id', 'NUMERIC,null'),
            ('port_id', 'NUMERIC,null'),
            ('time_stamp', 'NUMERIC,null'),
            ('udma_rx_bind', 'NUMERIC,null'),
            ('udma_tx_bind', 'NUMERIC,null'),
            ('rx_port_band_width', 'NUMERIC,null'),
            ('rx_packet_rate', 'NUMERIC,null'),
            ('rx_bytes', 'NUMERIC,null'),
            ('rx_packets', 'NUMERIC,null'),
            ('rx_errors', 'NUMERIC,null'),
            ('rx_dropped', 'NUMERIC,null'),
            ('tx_port_band_width', 'NUMERIC,null'),
            ('tx_packet_rate', 'NUMERIC,null'),
            ('tx_bytes', 'NUMERIC,null'),
            ('tx_packets', 'NUMERIC,null'),
            ('tx_errors', 'NUMERIC,null'),
            ('tx_dropped', 'NUMERIC,null'),
        ],
        'OriginMissionMap': [
            ('stream_id', 'NUMERIC,null'),
            ('task_id', 'NUMERIC,null'),
            ('lp_instr_id', 'NUMERIC,null'),
            ('lp_start_time', 'NUMERIC,null'),
            ('lp_end_time', 'NUMERIC,null'),
            ('setckebit_instr_id', 'NUMERIC,null'),
            ('setckebit_start_time', 'NUMERIC,null'),
            ('rel_id', 'NUMERIC,null'),
            ('rel_end_time', 'NUMERIC,null'),
        ],
        'OriginChannelMap': [
            ('channel_id', 'NUMERIC,null'),
            ('timestamp', 'NUMERIC,null'),
            ('max_bw', 'NUMERIC,null'),
            ('min_bw', 'NUMERIC,null'),
            ('avg_bw', 'NUMERIC,null'),
        ],
        'CCUTaskInfoMap': [
            ('version', 'NUMERIC,null'),
            ('work_flow_mode', 'NUMERIC,null'),
            ('item_id', 'TEXT,null'),
            ('group_name', 'TEXT,null'),
            ('rank_id', 'NUMERIC,null'),
            ('rank_size', 'NUMERIC,null'),
            ('stream_id', 'NUMERIC,null'),
            ('task_id', 'NUMERIC,null'),
            ('die_id', 'NUMERIC,null'),
            ('mission_id', 'NUMERIC,null'),
            ('instr_id', 'NUMERIC,null'),
        ],
        'CCUGroupInfoMap': [
            ('version', 'NUMERIC,null'),
            ('item_id', 'TEXT,null'),
            ('group_name', 'TEXT,null'),
            ('rank_id', 'NUMERIC,null'),
            ('rank_size', 'NUMERIC,null'),
            ('work_flow_mode', 'NUMERIC,null'),
            ('stream_id', 'NUMERIC,null'),
            ('task_id', 'NUMERIC,null'),
            ('die_id', 'NUMERIC,null'),
            ('instr_id', 'NUMERIC,null'),
            ('mission_id', 'NUMERIC,null'),
            ('reduce_op_type', 'NUMERIC,null'),
            ('input_data_type', 'NUMERIC,null'),
            ('output_data_type', 'NUMERIC,null'),
            ('data_size', 'NUMERIC,null'),
            ('channel_id', 'NUMERIC,null'),
            ('remote_rank_id', 'NUMERIC,null'),
        ],
        'CCUWaitSignalInfoMap': [
            ('version', 'NUMERIC,null'),
            ('item_id', 'TEXT,null'),
            ('group_name', 'TEXT,null'),
            ('rank_id', 'NUMERIC,null'),
            ('rank_size', 'NUMERIC,null'),
            ('work_flow_mode', 'NUMERIC,null'),
            ('stream_id', 'NUMERIC,null'),
            ('task_id', 'NUMERIC,null'),
            ('die_id', 'NUMERIC,null'),
            ('instr_id', 'NUMERIC,null'),
            ('mission_id', 'NUMERIC,null'),
            ('cke_id', 'NUMERIC,null'),
            ('mask', 'NUMERIC,null'),
            ('channel_id', 'NUMERIC,null'),
            ('remote_rank_id', 'NUMERIC,null'),
        ],
        'OriBiuDataMap': [
            ('group_id', 'NUMERIC,null'),
            ('core_type', 'TEXT,null'),
            ('block_id', 'NUMERIC,null'),
            ('ctrl_type', 'NUMERIC,null'),
            ('events', 'NUMERIC,null'),
            ('timestamp', 'NUMERIC,null'),
        ],
        'BiuInstrStatusMap': [
            ('group_id', 'NUMERIC,null'),
            ('core_type', 'TEXT,null'),
            ('block_id', 'NUMERIC,null'),
            ('instruction', 'TEXT,null'),
            ('timestamp', 'NUMERIC,null'),
            ('duration', 'NUMERIC,null'),
            ('checkpoint_info', 'NUMERIC,null'),
        ],
        'SocPmuMap': [
            ('task_type', 'NUMERIC,null'),
            ('stream_id', 'NUMERIC,null'),
            ('task_id', 'NUMERIC,null'),
            ('event_lists', 'TEXT,null')
        ],
        'SocPmuSummaryMap': [
            ('task_type', 'NUMERIC,null'),
            ('stream_id', 'NUMERIC,null'),
            ('task_id', 'NUMERIC,null'),
            ('hit_rate', 'NUMERIC,null'),
            ('miss_rate', 'NUMERIC,null')
        ],
        'AicVoltageMap': [
            ('syscnt', 'INTEGER,null'),
            ('voltage', 'INTEGER,null'),
        ],
        'BusVoltageMap': [
            ('syscnt', 'INTEGER,null'),
            ('voltage', 'INTEGER,null'),
        ],
        'StreamExpandSpecMap': [
            ('expand_status', 'NUMERIC,null')
        ],
    }
